### ISSUE TITLE
Header animation is slightly delayed

### ISSUE THREAD

**Issue by ifvictr** [hackclub/shop#4]
Happens when I scroll back to the top from the bottom of the page.

**Comment by merelinguist** [comment]
Can you provide a reproduction video? Thanks!

**Comment by merelinguist** [comment]
Hey, @ifvictr, I see what you’re talking about. This _can_ be fixed, but at the moment it’s a tradeoff between that small delay and performance on mobile devices, since we’re throttling the scroll function. For now, I think we should keep this line:

```js
this.handleScroll = throttle(300, this.handleScroll)
```

If we try new approaches in the future, though I’ll keep this problem in mind.
